# k8s/overlays/gke/patch-deployment-gke.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-api
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: classifier-api-sa
      containers:
        - name: classifier-api
          image: us-central1-docker.pkg.dev/stoked-monitor-375412/ml-apps/bps-classifier-api:prod
          imagePullPolicy: IfNotPresent