apiVersion: v1
kind: ServiceAccount
metadata:
  name: classifier-api-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: classifier-workload-sa@stoked-monitor-375412.iam.gserviceaccount.com